databases:
  - name: sms-db
    plan: free
    databaseName: sms_db

services:
  - type: web
    plan: free
    name: sms-app
    runtime: node
    nodeVersion: 20.18.0
    buildCommand: npm install && cd client && npm install && npm run build && cd .. && npx tsc && npm run migrate
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sms-db
          property: connectionString
      - key: NODE_ENV
        value: production
