CREATE TABLE IF NOT EXISTS teachers (

teacher_id SERIAL PRIMARY KEY,

first_name VARCHAR(100),
last_name VARCHAR(100),

email VARCHAR(150) UNIQUE,
phone VARCHAR(20),

specialization VARCHAR(100),

created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);